services:
  web:
    build: ./web
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/counter_db
    restart: on-failure # to handle cases that the database was not ready

  db:
    image: postgres:14
    ports:
      - "5432:5432" # Expose only if needed for external access (optional)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counter_db


volumes:
  db_data: