- name: Play
  hosts: local
  tasks:
    - name: Bring down existing containers (if any)
      community.docker.docker_compose_v2:
        project_src: .  
        files:
          - compose.yml
        state: absent  
        
    - name: Bring up Docker Compose application # הרצת docker-compose
      community.docker.docker_compose_v2:
        project_src: .  
        files:
          - compose.yml
        state: present
   
  
